- name: docker enable and start
  service: name=docker state=started enabled=yes

- name: docker start
  service: name=docker.service state=started enabled=yes
  
- name: docker stop
  service: name=docker.service state=stopped enabled=yes
 
 - name: docker restart
  service: name=docker.service state=restarted enabled=yes
